//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> TableId { get; set; }
        public Nullable<int> ReservationId { get; set; }
        public string OrderType { get; set; }
        public string Status { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public double Price { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Reservation Reservation { get; set; }
        public virtual RestaurantTable RestaurantTable { get; set; }
    }
}
