//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.EmployeeActivities = new HashSet<EmployeeActivity>();
        }
    
        public string CNIE { get; set; }
        public string LastName { get; set; }
        public string FIrstName { get; set; }
        public string PasswordHash { get; set; }
        public string Role { get; set; }
        public string IsActive { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual ICollection<EmployeeActivity> EmployeeActivities { get; set; }
    }
}
